name: Run test

on:
  workflow_dispatch:
  push:
    branches:
      - thirdmain

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Sqlplus
        run: |
          wget https://download.oracle.com/otn_software/linux/instantclient/214000/instantclient-basic-linux.x64-21.4.0.0.0dbru.zip
          wget https://download.oracle.com/otn_software/linux/instantclient/214000/instantclient-sqlplus-linux.x64-21.4.0.0.0dbru.zip 
          sudo mkdir -p /opt/oracle
          sudo unzip -d /opt/oracle instantclient-basic-linux.x64-21.4.0.0.0dbru.zip
          sudo unzip -d /opt/oracle instantclient-sqlplus-linux.x64-21.4.0.0.0dbru.zip
          export LD_LIBRARY_PATH=/opt/oracle/instantclient_21_4:$LD_LIBRARY_PATH
          export PATH=$PATH:/opt/oracle/instantclient_21_4
          export ORACLE_HOME=/opt/oracle/instantclient_21_4
          export TNS_ADMIN=/opt/oracle/instantclient_21_4
          sqlplus -V

      - name: Install Cloud Foundry CLI
        run: |
          # Install the Cloud Foundry CLI
          curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=7.4.0&source=github-rel" | tar -zx
          sudo mv cf /usr/local/bin/cf
          export PCF_CLI_PATH=/usr/local/bin/pcf

          cf --version

      - name: Set Environment and Run Script
        run: |
          export LD_LIBRARY_PATH=/opt/oracle/instantclient_21_4:$LD_LIBRARY_PATH
          export PATH=$PATH:/opt/oracle/instantclient_21_4
          export ORACLE_HOME=/opt/oracle/instantclient_21_4
          export TNS_ADMIN=/opt/oracle/instantclient_21_4/network/admin
          chmod +x sample_acook.sh
          # Add a check for LD_LIBRARY_PATH and PATH
          echo "LD_LIBRARY_PATH: $LD_LIBRARY_PATH"
          echo "PATH: $PATH"
          echo "Setting Oracle environment variables"
          echo "ORACLE_HOME: $ORACLE_HOME"
          echo "TNS_ADMIN: $TNS_ADMIN"
          export PCF_CLI_PATH=/usr/local/bin/pcf

          # Now, execute your script
          ./sample_acook.sh
