name: Run test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Sqlplus and PCF CLI
        run: |
          # Install Oracle Instant Client
          wget https://download.oracle.com/otn_software/linux/instantclient/214000/instantclient-basic-linux.x64-21.4.0.0.0dbru.zip
          wget https://download.oracle.com/otn_software/linux/instantclient/214000/instantclient-sqlplus-linux.x64-21.4.0.0.0dbru.zip
          sudo mkdir -p /opt/oracle
          sudo unzip instantclient-basic-linux.x64-21.4.0.0.0dbru.zip -d /opt/oracle
          sudo unzip instantclient-sqlplus-linux.x64-21.4.0.0.0dbru.zip -d /opt/oracle
          cd /opt/oracle/instantclient_21_4 && find . -type f | sort
          export LD_LIBRARY_PATH=/opt/oracle/instantclient_21_4:$LD_LIBRARY_PATH
          export TNS_ADMIN=/opt/oracle/instantclient_21_4/network/admin
          export PATH=/opt/oracle/instantclient_21_4:$PATH

          # Make sure SQL*Plus is in the PATH
          export PATH=/opt/oracle/instantclient_21_4:$PATH
          sqlplus -v  # Check SQL*Plus version to verify it's available

          # Install PCF CLI
          wget https://packages.cloudfoundry.org/stable?release=linux64-binary&version=7.0.2&source=github-rel -O cf-cli.tgz
          tar zxvf cf-cli.tgz
          sudo mv cf /usr/local/bin

          # Make the script executable and run it
          chmod +x sample_acook.sh
          ./sample_acook.sh
