name: Run test

on:
  workflow_dispatch:
  push:
    branches:
      - thirdmain

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Oracle Instant Client and SQL*Plus
        run: |
          sudo apt-get -y install libaio1 unzip
          wget https://download.oracle.com/otn_software/linux/instantclient/1911000/instantclient-basic-linux.x64-19.11.0.0.0dbru.zip
          unzip instantclient-basic-linux.x64-19.11.0.0.0dbru.zip
          sudo mkdir -p /opt/oracle
          sudo mv instantclient_19_11 /opt/oracle/
          echo 'export ORACLE_HOME=/opt/oracle/instantclient_19_11' >> $HOME/.bashrc
          echo 'export LD_LIBRARY_PATH=/opt/oracle/instantclient_19_11' >> $HOME/.bashrc
          source $HOME/.bashrc  # Source the .bashrc file to apply environment variables
        env:
          ORACLE_HOME: /opt/oracle/instantclient_19_11
            chmod +x sample_acook.sh
            ./sample_acook.sh
