name: Run test
on:
  workflow_dispatch:
  push:
    branches:
      - thirdmain
      
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Sqlplus and Run Script
        run: | 
          wget https://download.oracle.com/otn_software/linux/instantclient/214000/instantclient-basic-linux.x64-21.4.0.0.0dbru.zip
          wget https://download.oracle.com/otn_software/linux/instantclient/214000/instantclient-sqlplus-linux.x64-21.4.0.0.0dbru.zip
          sudo mkdir -p /opt/oracle
          sudo unzip instantclient-basic-linux.x64-21.4.0.0.0dbru.zip -d /opt/oracle
          sudo unzip instantclient-sqlplus-linux.x64-21.4.0.0.0dbru.zip -d /opt/oracle
          cd /opt/oracle/instantclient_21_4 && find . -type f | sort
          export LD_LIBRARY_PATH=/opt/oracle/instantclient_21_4:$LD_LIBRARY_PATH
          export PATH=$PATH:/opt/oracle/instantclient_21_4
          sqlplus -V
          
          # Define Oracle database connection details
          DB_USER="your_username"
          DB_PASS="your_password"
          DB_HOST="your_host"
          DB_PORT="your_port"
          DB_SID="your_sid"
          
          # SQL query to execute
          SQL_QUERY="SELECT * FROM your_table"
          
          # Execute SQLPlus command
          sqlplus -V