name: Run test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:latest  # Use a Docker container-based runner

    env:  # Set environment variables
      LD_LIBRARY_PATH: /opt/oracle/instantclient_21_4
      TNS_ADMIN: /opt/oracle/instantclient_21_4/network/admin
      PATH: /opt/oracle/instantclient_21_4:$PATH

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Sqlplus and unar
        run: |
          apt-get update
          apt-get install -y wget unar
          wget https://download.oracle.com/otn_software/linux/instantclient/214000/instantclient-basic-linux.x64-21.4.0.0.0dbru.zip
          wget https://download.oracle.com/otn_software/linux/instantclient/214000/instantclient-sqlplus-linux.x64-21.4.0.0.0dbru.zip
          mkdir -p /opt/oracle
          unar instantclient-basic-linux.x64-21.4.0.0.0dbru.zip -d /opt/oracle
          unar instantclient-sqlplus-linux.x64-21.4.0.0.0dbru.zip -d /opt/oracle
          cd /opt/oracle/instantclient_21_4 && find . -type f | sort
          
          # You can skip exporting environment variables here

          sqlplus -V

      - name: Run acook script
        run: |
          chmod +x sample_acook.sh
          ./sample_acook.sh
