name: Run test

on:
  workflow_dispatch:
  push:
    branches:
      - thirdmain

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Oracle Instant Client
        run: |
          sudo apt-get -y install libaio1 unzip
          wget https://download.oracle.com/otn_software/linux/instantclient/1911000/instantclient-basic-linux.x64-19.11.0.0.0dbru.zip
          unzip instantclient-basic-linux.x64-19.11.0.0.0dbru.zip
          sudo mkdir -p /opt/oracle
          sudo mv instantclient_19_11 /opt/oracle/
        env:
          ORACLE_HOME: /opt/oracle/instantclient_19_11
          LD_LIBRARY_PATH: ${{ runner.temp }}/actions-runner/_work/_temp

      - name: Source the .bashrc file
        run: source $HOME/.bashrc

      - name: Run sample_acook.sh script
        run: |
          chmod +x sample_acook.sh
          ./sample_acook.sh
