name: Run test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Oracle Instant Client
        run: |
          sudo apt-get update
          sudo apt-get install -y libaio1
          wget https://download.oracle.com/otn_software/linux/instantclient/211000/oracle-instantclient-basiclite_21.1.0.0.0-2_amd64.deb
          sudo dpkg -i oracle-instantclient-basiclite_21.1.0.0.0-2_amd64.deb
          echo /usr/lib/oracle/21/client64/lib | sudo tee -a /etc/ld.so.conf.d/oracle-instantclient.conf
          sudo ldconfig

      - name: Install CLPPlus
        run: |
          wget https://download.oracle.com/otn_software/developer-tools/sqlcl/sqlcl-21.4.1.285.1238.zip
          unzip sqlcl-21.4.1.285.1238.zip
          chmod +x sqlcl/bin/sql
          sudo mv sqlcl /usr/local
          sudo ln -s /usr/local/sqlcl/bin/sql /usr/local/bin/sql
          clpplus -v

