name: Run SQLcl Commands

on:
  workflow_dispatch:
  push:
    branches:
      - secondmain

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download and Install SQLcl
        run: |
          # Create a directory for SQLcl
          mkdir -p sqlcl

          # Download SQLcl from the repository asset (replace with the actual asset URL)
          wget -O sqlcl.zip https://github.com/tryingtobeacook/test_acook/releases/download/v1.0/sqlcl.zip

          # Extract SQLcl
          unzip sqlcl.zip
        env:
          SQLCL_HOME: ${{ runner.workspace }}/sqlcl

      - name: Run SQLcl Command
        run: |
          sql username/password@database <<EOF
          -- Your SQLcl commands go here
          EOF
        env:
          SQLCL_HOME: ${{ runner.workspace }}/sqlcl
