name: Run SQLcl Commands

on:
  workflow_dispatch:
  push:
    branches:
      - secondmain

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SQLcl
        run: |
          # Download SQLcl (adjust the version as needed)
          wget https://www.oracle.com/database/technologies/appdev/sqlcl-downloads.html -O sqlcl.zip
          unzip sqlcl.zip -d sqlcl
          
          # Move SQLcl to a specific location (e.g., /opt/sqlcl)
          sudo mkdir -p /opt/sqlcl
          sudo mv sqlcl/* /opt/sqlcl/
          
          # Add SQLcl to the PATH
          echo 'export PATH=$PATH:/opt/sqlcl' >> $HOME/.bashrc
        env:
          SQLCL_HOME: /opt/sqlcl

      - name: Run SQLcl Command
        run: |
          sql username/password@database <<EOF
          -- Your SQLcl commands go here
          EOF
        env:
          SQLCL_HOME: /opt/sqlcl
