name: Run test
on:
  workflow_dispatch:
  push:
    branches:
      - thirdmain
      
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Sqlplus
        run: | 
          wget https://download.oracle.com/otn_software/linux/instantclient/214000/instantclient-basic-linux.x64-21.4.0.0.0dbru.zip
          wget https://download.oracle.com/otn_software/linux/instantclient/214000/instantclient-sqlplus-linux.x64-21.4.0.0.0dbru.zip
          sudo mkdir -p /opt/oracle
          sudo unzip instantclient-basic-linux.x64-21.4.0.0.0dbru.zip -d /opt/oracle
          sudo unzip instantclient-sqlplus-linux.x64-21.4.0.0.0dbru.zip -d /opt/oracle
          cd /opt/oracle/instantclient_21_4 && find . -type f | sort
          export LD_LIBRARY_PATH=/opt/oracle/instantclient_21_4:$LD_LIBRARY_PATH
          export PATH=/opt/oracle/instantclient_21_4:$PATH

      - name: Set Environment and Run Script
        run: |
          echo 'export LD_LIBRARY_PATH=/opt/oracle/instantclient_21_4:$LD_LIBRARY_PATH' >> $GITHUB_ENV
          echo 'export PATH=/opt/oracle/instantclient_21_4:$PATH' >> $GITHUB_ENV

          chmod +x sample_acook.sh
          ./sample_acook.sh
