name: Run SQLPlus Commands
on:
  push:
    branches:
      - hmain
jobs:
  run-sqlplus:
    runs-on: ubuntu-latest
    steps:
      - name: Install SQLPlus
        run: |
          sudo apt-get update
          sudo apt-get install sqlplus
          sqlplus -V
      - name: Run SQLPlus Commands
        run: |
          sqlplus -s username/password@database <<EOF
          @/path/to/sqlplus_script.sql
          EOF
