name: Run test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Sqlplus
        run: |
          sudo apt-get update
          sudo apt-get install -y libaio1

          # Download and install Oracle Instant Client
          wget https://download.oracle.com/otn_software/linux/instantclient/214000/instantclient-basic-linux.x64-21.4.0.0.0dbru.zip
          wget https://download.oracle.com/otn_software/linux/instantclient/214000/instantclient-sqlplus-linux.x64-21.4.0.0.0dbru.zip

          # Create a temporary directory and unzip Oracle Instant Client there
          unzip -q instantclient-basic-linux.x64-21.4.0.0.0dbru.zip -d instantclient
          unzip -q instantclient-sqlplus-linux.x64-21.4.0.0.0dbru.zip -d instantclient

          # Move Oracle Instant Client files to system directories
          sudo mv instantclient/* /usr/lib/
          sudo ln -s /usr/lib/instantclient/sqlplus /usr/bin/sqlplus

          # Set environment variables more explicitly
          export LD_LIBRARY_PATH=/usr/lib/instantclient
          export PATH=/usr/bin:/usr/lib/instantclient:$PATH
          export TNS_ADMIN=/usr/lib/instantclient/network/admin

          sqlplus -V  # Check SQL*Plus version to verify it's available

      - name: Debug PATH
        run: echo $PATH

      - name: Run acook script
        run: |
          # Debugging: Check PATH environment variable
          echo "PATH: $PATH"

          # Debugging: Check if sqlplus is in the PATH
          which sqlplus

          chmod +x sample_acook.sh
          ./sample_acook.sh
