name: Run test

on:
  workflow_dispatch:
  push:
    branches:
      - main
      
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Sqlplus
        run: | 
          wget https://download.oracle.com/on_software/linux/instantclient/214000/instantclient-basic-linux.x64-21.4.0.0.0dbru.zip
          wget https://download.oracle.com/on_software/linux/instantclient/214000/instantclient-sqlplus-linux.x64-21.4.0.0.0dbru.zip
          sudo mkdir -p /opt/oracle
          sudo unzip instantclient-basic-linux.x64-21.4.0.0.0dbru.zip -d /opt/oracle
          sudo unzip instantclient-sqlplus-linux.x64-21.4.0.0.0dbru.zip -d /opt/oracle

      - name: Set Oracle Environment Variables
        run: |
          echo "/opt/oracle/instantclient_21_4" >> $GITHUB_PATH
          echo "/opt/oracle/instantclient_21_4" | sudo tee -a /etc/ld.so.conf.d/oracle-instantclient.conf
          sudo ldconfig
          echo 'export TNS_ADMIN=/opt/oracle/instantclient_21_4/network/admin' >> $GITHUB_ENV

      - name: Check Sqlplus Version
        run: sqlplus -V
