name: Run SQLcl Commands

on:
  workflow_dispatch:
  push:
    branches:
      - secondmain

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download SQLcl
        run: |
          # Create a directory for SQLcl
          mkdir -p sqlcl

          # Navigate to the directory
          cd sqlcl

          # Download SQLcl (adjust the version as needed)
          wget https://www.oracle.com/tools/downloads/sqlcl-downloads.html -O sqlcl-download.html

          # Extract the download link from the HTML file
          SQLCL_DOWNLOAD_URL=$(grep -o 'https://download.oracle.com[^"]*' sqlcl-download.html)

          # Download SQLcl
          wget "$SQLCL_DOWNLOAD_URL" -O sqlcl.zip

          # Extract SQLcl
          unzip sqlcl.zip
        env:
          SQLCL_HOME: ${{ runner.workspace }}/sqlcl

      - name: Run SQLcl Command
        run: |
          sql username/password@database <<EOF
          -- Your SQLcl commands go here
          EOF
        env:
          SQLCL_HOME: ${{ runner.workspace }}/sqlcl
