name: Run test

on:
  workflow_dispatch:
  push:
    branches:
      - thirdmain

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Sqlplus and Configure Oracle Environment
        run: |
          wget https://download.oracle.com/otn_software/linux/instantclient/214000/instantclient-basic-linux.x64-21.4.0.0.0dbru.zip
          wget https://download.oracle.com/otn_software/linux/instantclient/214000/instantclient-sqlplus-linux.x64-21.4.0.0.0dbru.zip 
          sudo mkdir -p /opt/oracle
          sudo unzip -d /opt/oracle instantclient-basic-linux.x64-21.4.0.0.0dbru.zip
          sudo unzip -d /opt/oracle instantclient-sqlplus-linux.x64-21.4.0.0.0dbru.zip
          export LD_LIBRARY_PATH=/opt/oracle/instantclient_21_4:$LD_LIBRARY_PATH
          export ORACLE_HOME=/opt/oracle/instantclient_21_4
          export TNS_ADMIN=/opt/oracle/instantclient_21_4 # Assuming TNS configuration files are here

      - name: Set Environment and Run Script
        run: |
          # Add a check for LD_LIBRARY_PATH, PATH, ORACLE_HOME, and TNS_ADMIN
          echo "LD_LIBRARY_PATH: $LD_LIBRARY_PATH"
          chmod +x sample_acook.sh

          # Run your own script without specifying the full path to sqlplus
          ./sample_acook.sh
