name: Install Oracle SQL*Plus

on:
  push:
    branches:
      - thirdmain

jobs:
  install-sqlplus:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y alien libaio1 rlwrap

      - name: Download Oracle Instant Client RPMs
        run: |
          # Download the RPMs from Oracle's website
          wget https://download.oracle.com/otn_software/linux/instantclient/214000/oracle-instantclient21.4-basic-21.4.0.0.0-1.x86_64.rpm
          wget https://download.oracle.com/otn_software/linux/instantclient/214000/oracle-instantclient21.4-sqlplus-21.4.0.0.0-1.x86_64.rpm

      - name: Convert RPMs to DEB using Alien
        run: |
          sudo alien -i oracle-instantclient21.4-basic-21.4.0.0.0-1.x86_64.rpm
          sudo alien -i oracle-instantclient21.4-sqlplus-21.4.0.0.0-1.x86_64.rpm

      - name: Configure LD_LIBRARY_PATH
        run: |
          echo "/usr/lib/oracle/21.4/client64/lib" | sudo tee /etc/ld.so.conf.d/oracle-instantclient.conf
          sudo ldconfig

      - name: Configure SQL*Plus alias
        run: |
          echo 'alias sqlplus="rlwrap -i -f ~/.sqlplus_history -H ~/.sqlplus_history -s 30000 sqlplus64"' | sudo tee /etc/profile.d/sqlplus_alias.sh
          touch ~/.sqlplus_history

      - name: Check SQL*Plus version
        run: |
          sqlplus -V

      - name: Run SQL*Plus command
        run: |
          sqlplus username/password@hostname:port/service

    env:
      ORACLE_HOME: /usr/lib/oracle/21.4/client64
      LD_LIBRARY_PATH: /usr/lib/oracle/21.4/client64/lib
