name: Run test

on:
  workflow_dispatch:
  push:
    branches:
      - main
      
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Sqlplus
        run: | 
          wget https://download.oracle.com/on_software/linux/instantclient/214000/instantclient-basic-linux.x64-21.4.0.0.0dbru.zip
          wget https://download.oracle.com/on_software/linux/instantclient/214000/instantclient-sqlplus-linux.x64-21.4.0.0.0dbru.zip
          sudo mkdir -p /opt/oracle
          sudo unzip -d /opt/oracle-instantclient-basic-linux.x64-21.4.0.0.0dbru.zip
          sudo unzip -d /opt/oracle-instantclient-sqlplus-linux.x64-21.4.0.0.0dbru.zip
          cd /opt/oracle/instantclient_21_4 && find . -type f | sort
          export LD_LIBRARY_PATH=/opt/oracle/instantclient_21_4:$LD_LIBRARY_PATH
          export PATH=$LD_LIBRARY_PATH:$PATH
          export TNS_ADMIN=/opt/oracle/instantclient_21_4/network/admin
          export PATH=/opt/oracle/instantclient_21_4:$PATH

          sqlplus -V
          
